Product.create!(name: 'リュック', price: 2000, picture: open("app/assets/images/item_1.png"))
Product.create!(name: 'バイク', price: 12000, picture: open("app/assets/images/item_2.png"))
Product.create!(name: 'シューズ', price: 6500, picture: open("app/assets/images/item_3.png"))
Product.create!(name: 'バッグ', price: 8000, picture: open("app/assets/images/item_4.png"))
Product.create!(name: 'PC', price: 80000, picture: open("app/assets/images/item_5.png"))
Product.create!(name: 'カメラ', price: 20000, picture: open("app/assets/images/item_6.png"))
Product.create!(name: 'テニスラケット', price: 19800, picture: open("app/assets/images/item_7.png"))
Product.create!(name: 'サッカーボール', price: 5300, picture: open("app/assets/images/item_8.png"))