Product.create!(name: 'リュック', categories: 1, price: 2000, picture: open("app/assets/images/item_1.png"))
Product.create!(name: 'バイク', categories: 4, price: 12000, picture: open("app/assets/images/item_2.png"))
Product.create!(name: 'シューズ', categories: 0, price: 6500, picture: open("app/assets/images/item_3.png"))
Product.create!(name: 'バッグ', categories: 1, price: 8000, picture: open("app/assets/images/item_4.png"))
Product.create!(name: 'PC', categories: 3, price: 80000, picture: open("app/assets/images/item_5.png"))
Product.create!(name: 'カメラ', categories: 3, price: 20000, picture: open("app/assets/images/item_6.png"))
Product.create!(name: 'テニスラケット', categories: 2, price: 19800, picture: open("app/assets/images/item_7.png"))
Product.create!(name: 'サッカーボール', categories: 2, price: 5300, picture: open("app/assets/images/item_8.png"))